/**
 * Extracts CSS for the MemoryCard components for use in MCP Apps iframes.
 *
 * Uses the dashboard's Vite-built CSS output (which is proven to render
 * correctly) rather than the programmatic Tailwind compile API.
 *
 * Prerequisite: run `cd dashboard && bun run build` first so dashboard/dist exists.
 *
 * Usage: bun scripts/extract-card-css.ts
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// Find the dashboard's built CSS file
const assetsDir = resolve(root, 'dashboard/dist/assets');
let cssFile: string;
try {
  const files = readdirSync(assetsDir);
  const cssFileName = files.find((f) => f.endsWith('.css'));
  if (!cssFileName) {
    throw new Error('No CSS file found in dashboard/dist/assets/');
  }
  cssFile = resolve(assetsDir, cssFileName);
} catch (err: any) {
  console.error(
    'Error: Dashboard must be built first. Run: cd dashboard && bun run build',
  );
  console.error(err.message);
  process.exit(1);
}

const css = readFileSync(cssFile, 'utf-8');
console.log(`Read dashboard CSS from ${cssFile} (${(css.length / 1024).toFixed(1)}KB)`);

// Write the output
const output = `// Auto-generated by scripts/extract-card-css.ts
// Do not edit manually — re-run: bun scripts/extract-card-css.ts
//
// Contains the dashboard's built Tailwind CSS for rendering MemoryCard
// components in MCP Apps iframes (membox_display tool).
//
// Source: dashboard/dist/assets/*.css (Vite build output)

export const CARD_CSS = ${JSON.stringify(css)};
`;

const outputPath = resolve(root, 'mcp/card-css.ts');
writeFileSync(outputPath, output, 'utf-8');
console.log(`Wrote ${outputPath} (${(output.length / 1024).toFixed(1)}KB)`);
